os: osx
osx_image: xcode10.3
language: swift
script: xcodebuild clean build test -project RecommededCardsModule.xcodeproj -scheme RecommededCardsModuleTests -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.4,name=iPhone 6” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
